### ISSUE TITLE
Descriptive variable names in SCM example

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt-future#2]
In the example script [radiative_equilibrium_rrtmg.py](https://github.com/CliMT/climt-future/blob/master/examples/radiative_equilibrium_rrtmg.py), the names tp_profiles and mol_profiles could be more descriptive. Perhaps they should be named thermodynamic_profiles and mole_fraction_profiles? The arrays could also be saved in a npz file, which allows dictionary lookup on its contents, so that the standalone npz file describes what's inside it without needing to know beforehand.

**Comment by JoyMonteiro** [comment]
Fixed.
