### ISSUE TITLE
Compilation of rrtmg_sw fails

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt-future#4]
In the RRTMG shortwave setup.py, 'rrtmg_sw_taumol.f90' needs to be compiled before 'rrtmg_sw_spcvrt.f90' because the second one depends on the first. If not, compilation fails the first time setup.py is called. This can be fixed by changing the order of the files in the list in setup.py.

**Comment by JoyMonteiro** [comment]
Oh, I had come across this, and thought it was fixed. Fixed now, thanks!
