### ISSUE TITLE
rename solar_cycle_fraction

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt-future#8]
In the RRTM SW wrapper, solar_cycle_fraction could use a more descriptive name, which specifically says what cycle it's a fraction of. But I don't know what that cycle is. What would be a good name?

**Comment by JoyMonteiro** [comment]
It is literally called solar cycle: https://en.wikipedia.org/wiki/Solar_cycle
you could call it solar magnetic activity cycle, but the conventional usage is "solar cycle".

Just keep it as is?

**Comment by mcgibbon** [comment]
If it's called solar_cycle_fraction inside RRTMG, and it's actually as descriptive as it now seems it is, then I'm fine with keeping it as-is.

**Comment by JoyMonteiro** [comment]
it is called `solcycfrac` within the fortran code, I think this version is a little more legible!
